# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoDateFormat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoDateFormat
pod 'SwiftDate', '~> 5.0'
  target 'DemoDateFormatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoDateFormatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
