# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Restaurants' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Restaurants
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseUI'
  pod 'Fabric'
  pod 'Crashlytics', '~> 3.10.1'
end
